### ISSUE TITLE
File not found exception (generation of bulk-retrievable-target.xml)

### ISSUE THREAD

**Issue by alex-acosta** [alan-morey/force-meta-backup#38]
C:\Ant Projects\force-meta-backup-master>ant backupMetadata
Buildfile: C:\Ant Projects\force-meta-backup-master\build.xml

clean:
   [delete] Deleting directory C:\Ant Projects\force-meta-backup-master\build

-setUp:
    [mkdir] Created dir: C:\Ant Projects\force-meta-backup-master\build

generatePackageXmlAndBuildXml:
     [exec] Microsoft Windows [Version 6.1.7601]
     [exec] Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
     [exec]
     [exec] C:\Ant Projects\force-meta-backup-master>

-setUpMetadataDir:
    [mkdir] Created dir: C:\Ant Projects\force-meta-backup-master\build\metadata

bulkRetrievable:

BUILD FAILED
C:\Ant Projects\force-meta-backup-master\build.xml:38: The following error occurred while executing this line:

BUILD FAILED
C:\Users\alex.acosta\workspace\Ant Projects\force-meta-backup-master\build.xml:38: The following error occurred while executing this line:
java.io.FileNotFoundException: C:\Ant Projects\force-meta-backup-master\build\bulk-retrievable-target.xml (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:250)
        at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:178)
        at org.apache.tools.ant.ProjectHelper.configureProject(ProjectHelper.java:93)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:392)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
        at org.apache.tools.ant.Main.runBuild(Main.java:853)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)

Total time: 1 second

C:\Ant Projects\force-meta-backup-master>

groovy version: 2.2.4 
JVM: 1.8.0_60 Oracle : Windows 7
Apache Ant(TM) version 1.9.6

**Comment by harishalgot** [comment]
please can any suggest how to resolve above issue file not exception
